All
gornalexander/lcode2dPy pull request #9
Opened 2021-11-10 10:40 UTC by nikiquark

Отправляю всё, что есть

2021-11-14 05:37 UTC, gornalexander requested changes
Функция generate_config()
- В  добавить строчку if path:
- Изменить название этой функции на get_с_config
- Добавить строчки cfg = lcode_template.format(**self.config_values) и return cfg
- Изменить cfg на file в строчках ниже 
with open(path, 'w') as cfg:
            cfg.write(lcode_template.format(**self.config_values))

2021-11-14 05:38 UTC, gornalexander approved these changes

2021-11-14 05:39 UTC, gornalexander approved these changes

2021-11-14 05:39 UTC, gornalexander approved these changes

2021-11-14 05:41 UTC, gornalexander requested changes
Прокомментируй, пожалуйста, изменения.

2021-11-14 05:41 UTC, gornalexander approved these changes

2021-11-14 05:42 UTC, gornalexander approved these changes

2021-11-14 05:43 UTC, gornalexander requested changes
- убрать is not None
- всегда возвращать cfg

2021-11-14 05:44 UTC, gornalexander requested changes
-

2021-11-14 05:45 UTC, gornalexander requested changes
Откатиться на прошлую версию numba

2021-11-18 07:31 UTC, nikiquark commented
Починил вылет на новой версии numba 0.54.1

2021-11-23 12:32 UTC, merged